apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rp-gitops-repo # v spoločnom klastri je nasadených viacero takýchto objektov
  namespace: wac-hospital
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/Robert-Prikryl/ambulance-gitops

# ak používate privátny repozitár nezabudnite doplniť autentifikačné údaje
# secretRef:
#    name: <pfx>-repository-pat

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: xprikryl-ambulance-virtual-patient
  namespace: wac-hospital
spec:
  interval: 1m0s
  ref:
    branch: main
  timeout: 1m0s
  url: https://github.com/Robert-Prikryl/ambulance-virtual-patient