apiVersion: apps/v1
kind: Deployment
metadata:
  name: xprikryl-ambulance-vp-api
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /xprikryl-ambulance-vp-api
            - name: BASE_URL
              value: /xprikryl-ambulance-vp-api-ui