apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: rp-ambulance-wl
  includeSelectors: true
  includeTemplates: true
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: xprikryl-ambulance-vp
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/rp-ambulance-ufe
- ../../../apps/xprikryl-ambulance-virtual-patient
- ../../../apps/rp-ambulance-webapi


components:
- ../../../components/version-release