kind: Service
apiVersion: v1
metadata:
  name: xprikryl-ambulance-virtual-patient   #  určuje aj záznam DNS v rámci virtuálne siete klastra
spec:
  selector:
    app.kubernetes.io/name: xprikryl-ambulance-vp
    app.kubernetes.io/part-of: wac-hospital
  ports:  
  - name: http
    protocol: TCP
    port: 80            # port pomenovanej služby, môže sa líšiť
                        # od portu na ktorom počúva kontajner
    targetPort: http    # viď meno portu v deployment.yaml