apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xprikryl-ambulance-virtual-patient-content
spec:
  microFrontend: xprikryl-ambulance-virtual-patient
  element: xprikryl-vp-list
  attributes:
    - name: api-base
      value: /api/virtual-patient
    - name: base-path
      value: /xprikryl-ambulance-virtual-patient
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xprikryl-vp-list(/.*)?$"