apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xprikryl-ambulance-vp-link
spec:
  microFrontend: polyfea-md-shell # referencia na microfrontend, z ktorého sa načíta element
  element: polyfea-md-app # element, ktorý bude vložený na stránku
  attributes: # atribúty elementu polyfea-md-app
    - name: headline
      value: Virtualný pacient
    - name: short-headline
      value: Virtualný pacient
    - name: supporting-text
      value: |
        Spravuje systém virtualných pacientov určených na študijné účely
    - name: material-icon
      value: home_health
    - name: href # presmerovanie po kliknutí na element polyfea-md-app
      value: ./xprikryl-ambulance-virtual-patient
  priority: 10
  displayRules: # pravidlá, kde sa má element vložiť v obálke
    - anyOf:
      - context-name: applications
      - context-name: rail-content
      - context-name: drawer-content