kind: Service
apiVersion: v1
metadata:
  name: xprikryl-ambulance-vp-api-ui
spec:
  selector:
    pod: xprikryl-ambulance-vp-api-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8081