kind: Service
apiVersion: v1
metadata:
  name: rp-ambulance-ufe   #  určuje aj záznam DNS v rámci virtuálne siete klastra
spec:
  selector:
    pod: rp-ambulance-ufe-label
  ports:
  - name: http
    protocol: TCP
    port: 80            # port pomenovanej služby, môže sa líšiť
                        # od portu na ktorom počúva kontajner
    targetPort: http    # viď meno portu v deployment.yaml